"""
Task Simulator for Benchmind AI Consultant
"""

import time
from typing import Dict, Any
from dataclasses import dataclass

from utils import (
    calculate_cost, 
    calculate_environmental_impact, 
    get_model_name, 
    assess_universal_quality,
    call_mistral_api
)


@dataclass
class TaskSimulationResult:
    """Result from simulating a task with a specific model."""
    model_id: str
    model_name: str
    task_description: str
    simulated_quality: float  # 0-1 score
    actual_latency_ms: float
    actual_cost_usd: float
    actual_energy_wh: float
    actual_co2_g: float
    simulation_details: Dict[str, Any]


class TaskSimulator:
    """Simulates different AI tasks to test model performance."""
    
    def __init__(self, mistral_api_key: str):
        self.mistral_api_key = mistral_api_key
    
    def simulate_universal_task(self, model_id: str, test_prompt: str, user_task: str, complexity: str) -> TaskSimulationResult:
        """Universal task simulator that works with ANY prompt generated by the intelligent system."""
        
        # Calculate expected tokens based on prompt length and complexity
        prompt_tokens = len(test_prompt.split()) * 1.3  # Rough token estimation
        if complexity == "simple":
            expected_response_tokens = 50
        elif complexity == "medium":
            expected_response_tokens = 150
        else:
            expected_response_tokens = 300
        
        total_expected_tokens = int(prompt_tokens + expected_response_tokens)
        
        # Execute the actual API call
        start_time = time.time()
        response = call_mistral_api(model_id, test_prompt, expected_response_tokens, self.mistral_api_key)
        end_time = time.time()
        
        # Calculate real metrics
        latency_ms = (end_time - start_time) * 1000
        usage = response.get('usage', {})
        actual_tokens = usage.get('total_tokens', total_expected_tokens)
        
        # Calculate real costs and environmental impact based on ACTUAL token usage
        cost_usd = calculate_cost(actual_tokens, model_id)
        energy_wh, co2_g = calculate_environmental_impact(actual_tokens, model_id)
        
        # Assess quality based on response
        response_text = response['choices'][0]['message']['content']
        quality_score = assess_universal_quality(response_text, user_task, complexity)
        
        return TaskSimulationResult(
            model_id=model_id,
            model_name=get_model_name(model_id),
            task_description=f"{user_task} ({complexity} complexity)",
            simulated_quality=quality_score,
            actual_latency_ms=latency_ms,
            actual_cost_usd=cost_usd,
            actual_energy_wh=energy_wh,
            actual_co2_g=co2_g,
            simulation_details={
                "test_prompt": test_prompt,
                "response": response_text,
                "tokens_used": actual_tokens,
                "prompt_tokens": usage.get('prompt_tokens', int(prompt_tokens)),
                "completion_tokens": usage.get('completion_tokens', expected_response_tokens),
                "complexity": complexity,
                "user_task": user_task
            }
        )
